trigger:
  branches:
    include:
      - main

# By default, use self-hosted agents
pool:
  vmImage: 'ubuntu-latest'
# Opting out of pull request validation
pr: none

# Variables specified at the pipeline level
variables:
  location: westeurope

stages:
#--------------------------- Development environment ------------------------------
- stage: Development
  displayName: Development environment
  variables:
    - group: development
    - group: development-kv
  jobs:
  # Run Helm
  - template: helm/azure-pipelines-wordpress.yml
    parameters:
      app: wordpress
      serviceConnection: OPENSHIFT
      environment: development
      project: wordpress
