trigger:
  branches:
    include:
      - main


# By default, use self-hosted agents
pool:
  vmImage: 'ubuntu-latest'
# Opting out of pull request validation
pr: none

resources:
  repositories:
    # Azure DevOps repository
    - repository: wp-pipeline
      type: git
      # project/repository
      name: joonas-test/wp-pipeline

extends:
  template: wordpress-site.yaml@wp-pipeline
