# Default values for worpdress-template.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

project: wordpress-template

wp:
  image:
    pullPolicy: Always
    tag: "latest"
  claimName: "wp-uploads"
  dbUser: "wordpress"
  dbPassword: ""
  dbHost: ""
  dbDatabase: ""
  tablePrefix: "wp_"
  storageClassName: "azure-file"
  storageSize: 5Gi
  domain: ""
  enableLivenessProbe: false
  enableReadinessProbe: false

git:
  uri: https://github.com/joonastikkanen/wp-pipeline-demo
  branch: main
  dockerfilePath: Dockerfile

service:
  type: ClusterIP
  port: 8080

resources: {}
  enabled: false
  limits:
    cpu: 1000m
  requests:
    cpu: 100m
