apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config-map
data:
  WORDPRESS_DB_USER: {{ .Values.wp.dbUser }}
  WORDPRESS_DB_NAME: {{ .Values.wp.dbDatabase }}
  WORDPRESS_DB_HOST: {{ .Values.wp.dbHost }}
  WORDPRESS_TABLE_PREFIX: {{ .Values.wp.tablePrefix }}
