apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: wordpress
spec:
  ports:
  - name: {{ .Values.service.port }}-tcp
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: wordpress
  type: {{ .Values.service.type }}
